# Generated by Django 6.0.7 on 2026-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
